# The content below is copied from the esp-docs repo

# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP 芯片勘误表'
copyright = u'2023 - {}, Espressif Systems (Shanghai) Co., Ltd'.format(current_year)
pdf_title = u'芯片勘误表'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'

doc_id = {'esp32': '3710', 'esp32s2': '5546', 'esp32s3': '6255', 'esp32c2': '6707', 'esp32c3': '6335', 'esp32c6': '7167', 'esp32h2': '7121'}
