# The content below is copied from the esp-docs repo

# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP 芯片勘误表'
copyright = u'2024 - {}, Espressif Systems (Shanghai) Co., Ltd'.format(current_year)
pdf_title = u'系列芯片勘误表'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'

doc_id = {'esp32s2': '5546', 'esp32s3': '6255', 'esp32c2': '6707', 'esp32c3': '6335', 'esp32c6': '7167', 'esp32h2': '7121', 'esp32': '3710'}

# Configuration for sphinx_tags
tags_overview_title = "各芯片版本的已知错误"
tags_index_head = "芯片版本"
tags_intro_text = "影响版本："
tags_page_title = "芯片版本"
tags_page_header = "已知错误"

# Document version number
version_num = {'esp32c3': '版本 v1.1', 'esp32c6': '版本 v1.1', 'esp32s2': '版本 v1.2', 'esp32s3': '版本 v1.2', 'esp32h2': '版本 v1.0', 'esp32c2': '版本 v1.1', 'esp32': '版本 v2.8'}

# Table, figure, and section numbering configurations
numfig_format = {
    'figure': '图 %s',
    'table': '表 %s',
}

# ----------------- Chinese-specific LaTeX configurations -----------------

cn_footer_toc_config = r'''
% Header and footer
\makeatletter
  \fancypagestyle{normal}{
    \fancyhf{}
    \fancyhead[L]{\nouppercase{\leftmark}}
    \fancyfoot[C]{\py@HeaderFamily\thepage \\ \href{https://www.espressif.com/zh-hans/company/documents/documentation_feedback?docId=\DocId&sections=&version=\docversion}{提交文档反馈}}
    \fancyfoot[L]{乐鑫信息科技}
    \fancyfoot[R]{{\idfTarget}{\@title}{\docversion{}}}
    \renewcommand{\headrulewidth}{0.4pt}
    \renewcommand{\footrulewidth}{0.4pt}
  }
\makeatother

\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}

% ToC
\addto\captionsenglish{\renewcommand{\contentsname}{目录}}
'''

# Get Current Target
def conf_setup(app, config):
    print("Current target:", config.idf_target)

    # Get the version number
    doc_version = version_num.get(config.idf_target, 'Unknown Version')
    print("Doc version:", doc_version)
    
    # Dynamically update the LaTeX preamble
    doc_version_config = '''
    %% Version number
    \\newcommand{{\\docversion}}{{{}}}
    '''.format(doc_version)  # Format doc_version here

    # Update the preamble with the version info
    config.latex_elements['preamble'] += doc_version_config

user_setup_callback = conf_setup

latex_elements['preamble'] = preamble + cn_footer_toc_config + preamble_extra
