name: Issue report
description: Report incorrect or confusing descriptions, typos, grammar errors, formatting issues, etc.
label: ['Type: Issue']
body: 
  - type: dropdown
    id: document_name
    attributes:
      label: Document title
      multiple: false
      options:
        - ESP32-S2 Series SoC Errata
        - ESP32-S3 Series SoC Errata
        - ESP32-C3 Series SoC Errata
        - ESP32-C6 Series SoC Errata
        - ESP32-H2 Series SoC Errata
        - ESP32-C2 Series SoC Errata
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Format
      multiple: false
      options:
        - HTML
        - PDF
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version number
      description: Which document version has this issue? Fill in if you did not read the document online.
      placeholder: latest
    validations:
      required: false
  - type: input
    id: section
    attributes:
      label: Section
      description: Which section has this issue?
      placeholder: [Clock] Inaccurate Calibration of RC_FAST_CLK Clock
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the issue in details
    validations:
      required: true
