# The content below is copied from the esp-docs repo

# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module

try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP Chip Errata'
copyright = u'2024 - {}, Espressif Systems (Shanghai) Co., Ltd'.format(current_year)
pdf_title = u' Series SoC Errata '

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

doc_id = {'esp32s2': '5545', 'esp32s3': '6121', 'esp32c2': '6705', 'esp32c3': '6333', 'esp32c6': '7165', 'esp32h2': '7119', 'esp32': '3709'}

# Configuration for sphinx_tags
tags_overview_title = "Errata Descriptions by Chip Revisions"
tags_index_head = "Chip Revision"
tags_intro_text = "Affected revisions: "
tags_page_title = "Chip Revision"
tags_page_header = "Known Errors"

# Document version number
version_num = {'esp32c3': 'Version 1.1', 'esp32c6': 'Version 1.1', 'esp32s2': 'Version 1.2', 'esp32s3': 'Version 1.2', 'esp32h2': 'Version 0.5', 'esp32c2': 'Version 1.1', 'esp32': 'Version 2.8'}

# Table, figure, and section numbering configurations
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
}

# ----------------- English-specific LaTeX configurations -----------------

en_footer_toc_config = r'''
% Header and footer
\makeatletter
  \fancypagestyle{normal}{
    \fancyhf{}
    \fancyhead[L]{\nouppercase{\leftmark}}
    \fancyfoot[C]{\py@HeaderFamily\thepage \\ \href{https://www.espressif.com/en/company/documents/documentation_feedback?docId=\DocId&sections=&version=\VersionNum}{Submit Document Feedback}}
    \fancyfoot[L]{Espressif Systems}
    \fancyfoot[R]{{\idfTarget}{\@title}{\VersionNum}}
    \renewcommand{\headrulewidth}{0.4pt}
    \renewcommand{\footrulewidth}{0.4pt}
  }
\makeatother

\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}

'''

latex_elements['preamble'] = preamble + en_footer_toc_config + preamble_extra
